<a href="https://colab.research.google.com/github/23-24/23-24/blob/main/MINI_IMAGE_CAPTIONER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
import seaborn as sn
import torch
from PIL import Image
import os
from keras.applications.vgg16 import VGG16, preprocess_input
from keras.preprocessing import image
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras.utils import to_categorical

import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
from zipfile import ZipFile

In [ ]:
!unzip /content/drive/MyDrive/Ff/image.zip

Streaming output truncated to the last 5000 lines.
  inflating: Images/2844846111_8c1cbfc75d.jpg  
  inflating: Images/2844963839_ff09cdb81f.jpg  
  inflating: Images/2845246160_d0d1bbd6f0.jpg  
  inflating: Images/2845691057_d4ab89d889.jpg  
  inflating: Images/2845845721_d0bc113ff7.jpg  
  inflating: Images/2846037553_1a1de50709.jpg  
  inflating: Images/2846785268_904c5fcf9f.jpg  
  inflating: Images/2846843520_b0e6211478.jpg  
  inflating: Images/2847514745_9a35493023.jpg  
  inflating: Images/2847615962_c330bded6e.jpg  
  inflating: Images/2847859796_4d9cb0d31f.jpg  
  inflating: Images/2848266893_9693c66275.jpg  
  inflating: Images/2848571082_26454cb981.jpg  
  inflating: Images/2848895544_6d06210e9d.jpg  
  inflating: Images/2848977044_446a31d86e.jpg  
  inflating: Images/2849194983_2968c72832.jpg  
  inflating: Images/2850719435_221f15e951.jpg  
  inflating: Images/2851198725_37b6027625.jpg  
  inflating: Images/2851304910_b5721199bc.jpg  
  inflating: Images/2851931813_eaf8ed

In [ ]:
import os
print(os.listdir('/content/drive/MyDrive/Ff/'))

['quiz.pdf', 'CamScanner 07-29-2020 21.31.33.pdf', 'performing art.pdf', 'word.pdf', 'CamScanner 09-17-2020 10.24.41 (1).pdf', 'logic notes module 1.pdf', 'CamScanner 09-20-2020 11.41.52 (1).pdf', 'Qw', 'CamScanner 09-20-2020 11.41.52.pdf', 'mod1 (1).pdf', 'problems on periodic funnction.pdf', 'periodic function.pdf', 'pgm_day2 algorithm.pdf', 'day2_code input and output', 'maths .pdf', 'CamScanner 10-05-2020 11.05.35 (1).pdf', 'CamScanner 10-06-2020 11.02.39 (1).pdf', 'Abel simon Zachariah', 'mod1.pdf', 'Basic program_codeinputandoutput', 'CamScanner 10-08-2020 11.04.07.pdf', 'CamScanner 09-17-2020 10.24.41.pdf', 'logic 2.pdf', 'CamScanner 10-07-2020 11.03.59.pdf', 'Basic program_algorithm.pdf', 'CamScanner 10-05-2020 11.05.35.pdf', 'maths.pdf', 'CamScanner 10-06-2020 11.02.39.pdf', 'server.c', 'preliminary presentation schedule final.xls', 'lex2.l', 'day21 (1).l', 'day21.l', 'day22.l', 'day23.l', 'Attendance S7CSAlpha.pdf', '.ipynb_checkpoints', 'image.zip', 'archieve.zip', 'images',

In [ ]:
from PIL import Image
import os

# Define the path to the directory containing the images
input_dir = "/content/drive/MyDrive/Ff/imgold/Images"

# Define the path to the directory where the resized images will be saved
output_dir = "/content/drive/MyDrive/Ff/images"


In [ ]:
for filename in os.listdir(input_dir):
    # Open the image file
    with Image.open(os.path.join(input_dir, filename)) as img:
        # Get the size of the image
        width, height = img.size
        # Print the size of the image
        print(f"{filename}: {width}x{height}")

Streaming output truncated to the last 5000 lines.
3128514681_a51b415c31.jpg: 500x375
3133044777_8cc930a4ec.jpg: 500x344
3117562746_62f57a02b5.jpg: 500x469
3141293960_74459f0a24.jpg: 380x500
3119887967_271a097464.jpg: 500x330
315021440_122d56ebd7.jpg: 500x333
3147913471_322ea231d9.jpg: 400x500
3116985493_04b1dc3345.jpg: 500x334
3113322995_13781860f2.jpg: 368x500
3139238055_2817a0c7d8.jpg: 500x333
3144705706_391d7b77c7.jpg: 375x500
3122497129_d08f5729b8.jpg: 500x333
3134586018_ae03ba20a0.jpg: 500x376
3141440149_00becbbb93.jpg: 500x375
3125309108_1011486589.jpg: 362x500
3136043366_b3f8607a0e.jpg: 500x357
3134644844_493eec6cdc.jpg: 500x333
3139118874_599b30b116.jpg: 500x498
3134585858_a8c3493ca5.jpg: 400x500
3131990048_369b081021.jpg: 333x500
3138746531_f6b816c126.jpg: 500x333
3138562460_44227a35cf.jpg: 333x500
3113769557_9edbb8275c.jpg: 389x500
3112821789_1f7c3bbb99.jpg: 500x375
3120648767_812c72eabe.jpg: 500x333
3132760860_3e743a935d.jpg: 500x333
3132006797_04822b5866.jpg: 500x375
31199

In [ ]:
size=(256,256)

In [ ]:
for filename in os.listdir(input_dir):
    with Image.open(os.path.join(input_dir, filename)) as img:
      img_resized = img.resize(size)
      img_resized.save(os.path.join(output_dir, filename))

In [ ]:
for filename in os.listdir(output_dir):
    # Open the image file
    with Image.open(os.path.join(output_dir, filename)) as img:
        # Get the size of the image
        width, height = img.size
        # Print the size of the image
        print(f"{filename}: {width}x{height}")

Streaming output truncated to the last 5000 lines.
3053813297_7ce5f87710.jpg: 256x256
3066429707_842e50b8f7.jpg: 256x256
3057618932_3b80ae85de.jpg: 256x256
3067971348_69af5bb309.jpg: 256x256
3056569684_c264c88d00.jpg: 256x256
3078844565_16e9cdcea2.jpg: 256x256
3068994801_b2bc079e67.jpg: 256x256
3101796900_59c15e0edc.jpg: 256x256
3085667767_66041b202e.jpg: 256x256
3091921457_83eee69591.jpg: 256x256
3090593241_93a975fe2b.jpg: 256x256
3088922727_4bdf2ccc94.jpg: 256x256
3090386315_87ed417814.jpg: 256x256
3099504809_565e17e49d.jpg: 256x256
3102204862_f1d220230b.jpg: 256x256
3108732084_565b423162.jpg: 256x256
3107889179_106d223345.jpg: 256x256
3107558821_f3b205d4ed.jpg: 256x256
3091912922_0d6ebc8f6a.jpg: 256x256
3096163135_584901a5ae.jpg: 256x256
3106787167_e5f2312622.jpg: 256x256
3101378069_f8caa14c0a.jpg: 256x256
3111402233_6285bcba7a.jpg: 256x256
3086523890_fd9394af8b.jpg: 256x256
3091962081_194f2f3bd4.jpg: 256x256
309771854_952aabe3cc.jpg: 256x256
3107059919_0594269f72.jpg: 256x256
30909

In [ ]:
vgg16_model = VGG16(weights='imagenet', include_top=False)

# Define the layer from which to extract features
layer_name = 'block5_pool'

58889256/58889256 [==============================] - 0s 0us/step


In [ ]:
pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from tensorflow.keras.applications.resnet50 import ResNet50, preprocess_input
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np
import os

# Load the pre-trained ResNet50 model
model = ResNet50(weights='imagenet', include_top=False, pooling='avg')


94765736/94765736 [==============================] - 1s 0us/step


In [ ]:
output_file = 'features.npy'

# Initialize an empty list to store the features
features_list = []

# Loop over each file in the input directory
for filename in os.listdir(output_dir):
    # Load the image file and convert it to a numpy array
    img_path = os.path.join(output_dir, filename)
    img = load_img(img_path, target_size=(224, 224))
    img_array = img_to_array(img)
    
    # Preprocess the image array
    img_array = preprocess_input(img_array)
    
    # Add a batch dimension to the array
    img_array = np.expand_dims(img_array, axis=0)
    
    # Use the ResNet50 model to extract features from the image
    features = model.predict(img_array)
    features_list.append(features)

# Convert the list of features to a numpy array and save it to a file
features_array = np.concatenate(features_list, axis=0)
np.save(output_file, features_array)


Streaming output truncated to the last 5000 lines.
1/1 [==============================] - 0s 198ms/step


In [ ]:


# Read captions from text document
with open('captions.txt', 'r') as f:
    captions = f.readlines()

# Preprocess captions
tokenizer = Tokenizer()
tokenizer.fit_on_texts(captions)
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(captions)
padded_sequences = pad_sequences(sequences, padding='post')

# Save preprocessed captions to numpy array file
np.save('captions.npy', padded_sequences)

In [ ]:
captions = np.load('captions.npy')

print(captions)

[[ 1166 21340     0 ...     0     0     0]
 [ 2652  2653     2 ...     0     0     0]
 [ 2652  2653     2 ...     0     0     0]
 ...
 [19160 19161     2 ...     0     0     0]
 [19160 19161     2 ...     0     0     0]
 [19160 19161     2 ...     0     0     0]]


In [ ]:
print(captions.shape)

(40456, 40)


In [ ]:
word_index

{'a': 1,
 'jpg': 2,
 'in': 3,
 'the': 4,
 'on': 5,
 'is': 6,
 'and': 7,
 'dog': 8,
 'with': 9,
 'man': 10,
 'of': 11,
 'two': 12,
 'white': 13,
 'black': 14,
 'boy': 15,
 'are': 16,
 'woman': 17,
 'girl': 18,
 'to': 19,
 'wearing': 20,
 'at': 21,
 'people': 22,
 'water': 23,
 'red': 24,
 'young': 25,
 'brown': 26,
 'an': 27,
 'his': 28,
 'blue': 29,
 'dogs': 30,
 'running': 31,
 'through': 32,
 'playing': 33,
 'while': 34,
 'shirt': 35,
 'down': 36,
 'standing': 37,
 'ball': 38,
 'little': 39,
 'grass': 40,
 'snow': 41,
 'child': 42,
 'person': 43,
 'jumping': 44,
 'over': 45,
 'three': 46,
 'front': 47,
 'sitting': 48,
 'holding': 49,
 'up': 50,
 'field': 51,
 'small': 52,
 'by': 53,
 'large': 54,
 'green': 55,
 'one': 56,
 'group': 57,
 'yellow': 58,
 'her': 59,
 'walking': 60,
 'children': 61,
 'men': 62,
 'into': 63,
 'air': 64,
 'beach': 65,
 'near': 66,
 'mouth': 67,
 'jumps': 68,
 'another': 69,
 'for': 70,
 'street': 71,
 'runs': 72,
 'its': 73,
 'from': 74,
 'riding': 75,
 'st

In [ ]:
sequences

[[1166, 21340],
 [2652,
  2653,
  2,
  1,
  42,
  3,
  1,
  89,
  171,
  6,
  118,
  50,
  1,
  392,
  11,
  393,
  3,
  27,
  21341,
  669],
 [2652, 2653, 2, 1, 18, 315, 63, 1, 195, 116],
 [2652, 2653, 2, 1, 39, 18, 118, 63, 1, 195, 2436],
 [2652, 2653, 2, 1, 39, 18, 118, 4, 393, 19, 59, 2436],
 [2652, 2653, 2, 1, 39, 18, 3, 1, 89, 171, 315, 63, 1, 195, 19162],
 [2654, 2655, 2, 1, 14, 8, 7, 1, 842, 8, 16, 342],
 [2654, 2655, 2, 1, 14, 8, 7, 1, 1574, 234, 8, 33, 9, 136, 81, 5, 4, 150],
 [2654,
  2655,
  2,
  1,
  14,
  8,
  7,
  1,
  13,
  8,
  9,
  26,
  1000,
  16,
  639,
  21,
  136,
  81,
  3,
  4,
  71],
 [2654, 2655, 2, 12, 30, 11, 740, 2656, 88, 21, 136, 81, 5, 4, 150],
 [2654, 2655, 2, 12, 30, 5, 726, 804, 320, 136, 81],
 [2657,
  2658,
  2,
  1,
  39,
  18,
  163,
  3,
  605,
  105,
  3,
  47,
  11,
  1,
  593,
  1193,
  9,
  59,
  219,
  3,
  1,
  975],
 [2657, 2658, 2, 1, 39, 18, 6, 48, 3, 47, 11, 1, 54, 593, 1193],
 [2657,
  2658,
  2,
  1,
  52,
  18,
  3,
  4,
  40,
  113

In [ ]:
padded_sequences

array([[ 1166, 21340,     0, ...,     0,     0,     0],
       [ 2652,  2653,     2, ...,     0,     0,     0],
       [ 2652,  2653,     2, ...,     0,     0,     0],
       ...,
       [19160, 19161,     2, ...,     0,     0,     0],
       [19160, 19161,     2, ...,     0,     0,     0],
       [19160, 19161,     2, ...,     0,     0,     0]], dtype=int32)

In [ ]:
# Load features and captions
features = np.load('features.npy')
captions = np.load('captions.npy')

# Determine the number of samples
num_samples = len(features)

# Shuffle the indices
indices = np.arange(num_samples)
np.random.shuffle(indices)

# Split the data into train, validation, and test sets
train_indices = indices[:int(0.7*num_samples)]
val_indices = indices[int(0.7*num_samples):int(0.85*num_samples)]
test_indices = indices[int(0.85*num_samples):]

train_features = features[train_indices]
train_captions = captions[train_indices]
val_features = features[val_indices]
val_captions = captions[val_indices]
test_features = features[test_indices]
test_captions = captions[test_indices]

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, GRU, Dense

# Define the maximum length of the captions and the size of the vocabulary
max_caption_len = 20
vocab_size = 5000

# Define the embedding size and the hidden size of the LSTM/GRU layer
embedding_size = 256
hidden_size = 512
# Define the model architecture
model = Sequential()
model.add(Embedding(vocab_size, embedding_size, input_length=max_caption_len))
model.add(LSTM(hidden_size))
model.add(Dense(hidden_size, activation='relu'))
model.add(Dense(vocab_size, activation='softmax'))

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam')

# Print the model summary
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 256)           1280000   
                                                                 
 lstm (LSTM)                 (None, 512)               1574912   
                                                                 
 dense (Dense)               (None, 512)               262656    
                                                                 
 dense_1 (Dense)             (None, 5000)              2565000   
                                                                 
Total params: 5,682,568
Trainable params: 5,682,568
Non-trainable params: 0
_________________________________________________________________


In [ ]:
max_length = max(len(caption) for caption in train_captions)

# Add 2 to max_length to account for start and end tokens
max_length += 2

In [ ]:
vocab_size = max(np.max(train_captions), np.max(val_captions)) + 1

captions_train_one_hot = to_categorical(train_captions, num_classes=vocab_size)
captions_val_one_hot = to_categorical(val_captions, num_classes=vocab_size)



In [ ]:
captions_train_one_hot

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0.

In [ ]:
captions_val_one_hot

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0.

In [ ]:
import tensorflow_addons as tfa
import keras
from tensorflow.keras.optimizers import Adam
from tensorflow_addons.optimizers import AdamW